package flow;

/**
 * This is a special reserved class that is repsonsible for loading application 
 * variables as well as the forward to the actual first form of the application.<br>
 * This class should not be manually edited as changes may be overridden by the 
 * code generator.<br>
 * Last generated by Orchestration Designer at: 2023-JAN-19  04:23:12 PM
 */
public class Start extends com.avaya.sce.runtime.Entry {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-JAN-19  04:23:12 PM
	 */
	public Start() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically.  Any changes may be overwritten.
	 * Returns the submit object that will redirect application flow to the first
	 * form in the application.  This also adds various standard variables to the
	 * list of data to be submitted to the runtime variable table.
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 * @return the Submit object that contains the standard variables and the first form
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = new com.avaya.sce.runtime.Submit("Greetings");
		return ( submit );
	}
	/**
	 * This method initializes the SCE session with the variables that
	 * are defined in the application.<BR>
	 * 
	 * This method is generated automatically and should not be manually
	 * edited because changes may be overwritten by future code 
	 * generation.
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public void initializeVariables(com.avaya.sce.runtimecommon.SCESession session) {
		com.avaya.sce.runtimecommon.IVariable variable = null;
		String[] variableFields = null;

		variableFields = new String[] {
			IProjectVariables.AUDIO_URLS_FIELD_BLOOD_GROUP_SELECT,
			IProjectVariables.AUDIO_URLS_FIELD_BRANCH_SELECT,
			IProjectVariables.AUDIO_URLS_FIELD_GREETINGS,
			IProjectVariables.AUDIO_URLS_FIELD_NEXT,
			IProjectVariables.AUDIO_URLS_FIELD_NULL_INPUT,
			IProjectVariables.AUDIO_URLS_FIELD_PREVIOUS,
			IProjectVariables.AUDIO_URLS_FIELD_REGION_SELECT,
			IProjectVariables.AUDIO_URLS_FIELD_REPEAT,
			IProjectVariables.AUDIO_URLS_FIELD_SERVICE_SELECT,
			IProjectVariables.AUDIO_URLS_FIELD_WRONG_INPUT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AUDIO_URLS, variableFields, new String[] {"D:\\IVR Audios\\BloodBank\\BloodGroupSelect.wav", "D:\\IVR Audios\\BloodBank\\BranchSelect.wav", "D:\\IVR Audios\\BloodBank\\Greetings.wav", "D:\\IVR Audios\\BloodBank\\Next.wav", "D:\\IVR Audios\\BloodBank\\NullInput.wav", "D:\\IVR Audios\\BloodBank\\Previous.wav", "D:\\IVR Audios\\BloodBank\\RegionSelect.wav", "D:\\IVR Audios\\BloodBank\\Repeat.wav", "D:\\IVR Audios\\BloodBank\\ServiceSelect.wav", "D:\\IVR Audios\\BloodBank\\WrongInput.wav"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DTMFAUDIO_FIELD_PRESS_1,
			IProjectVariables.DTMFAUDIO_FIELD_PRESS_2,
			IProjectVariables.DTMFAUDIO_FIELD_PRESS_3,
			IProjectVariables.DTMFAUDIO_FIELD_PRESS_4,
			IProjectVariables.DTMFAUDIO_FIELD_PRESS_5,
			IProjectVariables.DTMFAUDIO_FIELD_PRESS_6 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DTMFAUDIO, variableFields, new String[] {"D:\\IVR Audios\\BloodBank\\Press1.wav", "D:\\IVR Audios\\BloodBank\\Press2.wav", "D:\\IVR Audios\\BloodBank\\Press3.wav", "D:\\IVR Audios\\BloodBank\\Press4.wav", "D:\\IVR Audios\\BloodBank\\Press5.wav", "D:\\IVR Audios\\BloodBank\\Press6.wav"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.BRANCH_SELECTION_FIELD_CONFIDENCE,
			IProjectVariables.BRANCH_SELECTION_FIELD_INPUTMODE,
			IProjectVariables.BRANCH_SELECTION_FIELD_INTERPRETATION,
			IProjectVariables.BRANCH_SELECTION_FIELD_NOINPUTCOUNT,
			IProjectVariables.BRANCH_SELECTION_FIELD_NOMATCHCOUNT,
			IProjectVariables.BRANCH_SELECTION_FIELD_UTTERANCE,
			IProjectVariables.BRANCH_SELECTION_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.BRANCH_SELECTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SELECT_BLOOD__GROUP_FIELD_CONFIDENCE,
			IProjectVariables.SELECT_BLOOD__GROUP_FIELD_INPUTMODE,
			IProjectVariables.SELECT_BLOOD__GROUP_FIELD_INTERPRETATION,
			IProjectVariables.SELECT_BLOOD__GROUP_FIELD_NOINPUTCOUNT,
			IProjectVariables.SELECT_BLOOD__GROUP_FIELD_NOMATCHCOUNT,
			IProjectVariables.SELECT_BLOOD__GROUP_FIELD_UTTERANCE,
			IProjectVariables.SELECT_BLOOD__GROUP_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SELECT_BLOOD__GROUP, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REDIRECTINFO_FIELD_PRESENTATIONINFO,
			IProjectVariables.REDIRECTINFO_FIELD_REASON,
			IProjectVariables.REDIRECTINFO_FIELD_SCREENINGINFO,
			IProjectVariables.REDIRECTINFO_FIELD_URI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REDIRECTINFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SERVICE_SELECT_FIELD_CONFIDENCE,
			IProjectVariables.SERVICE_SELECT_FIELD_INPUTMODE,
			IProjectVariables.SERVICE_SELECT_FIELD_INTERPRETATION,
			IProjectVariables.SERVICE_SELECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.SERVICE_SELECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.SERVICE_SELECT_FIELD_UTTERANCE,
			IProjectVariables.SERVICE_SELECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SERVICE_SELECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DATE_FIELD_AUDIO,
			IProjectVariables.DATE_FIELD_DAYOFMONTH,
			IProjectVariables.DATE_FIELD_DAYOFWEEK,
			IProjectVariables.DATE_FIELD_DAYOFWEEKNUM,
			IProjectVariables.DATE_FIELD_DAYOFYEAR,
			IProjectVariables.DATE_FIELD_MONTH,
			IProjectVariables.DATE_FIELD_MONTHINYEAR,
			IProjectVariables.DATE_FIELD_YEAR };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DATE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CALL__HISTORY_FIELD_DURATION,
			IProjectVariables.CALL__HISTORY_FIELD_ENDDATE,
			IProjectVariables.CALL__HISTORY_FIELD_EXITNODE,
			IProjectVariables.CALL__HISTORY_FIELD_EXITREASON,
			IProjectVariables.CALL__HISTORY_FIELD_IP,
			IProjectVariables.CALL__HISTORY_FIELD_STARTDATE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CALL__HISTORY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.BRANCH_SELECT, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SESSION_FIELD_AAI,
			IProjectVariables.SESSION_FIELD_ANI,
			IProjectVariables.SESSION_FIELD_CALLTAG,
			IProjectVariables.SESSION_FIELD_CHANNEL,
			IProjectVariables.SESSION_FIELD_CHANNELTYPE,
			IProjectVariables.SESSION_FIELD_CONVERSEFIRST,
			IProjectVariables.SESSION_FIELD_CONVERSESECOND,
			IProjectVariables.SESSION_FIELD_CURRENTLANGUAGE,
			IProjectVariables.SESSION_FIELD_DNIS,
			IProjectVariables.SESSION_FIELD_EXIT_CUSTOMER_ID,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_1,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_2,
			IProjectVariables.SESSION_FIELD_EXIT_PARENT_ID,
			IProjectVariables.SESSION_FIELD_EXIT_PREFERRED_PATH,
			IProjectVariables.SESSION_FIELD_EXIT_REASON,
			IProjectVariables.SESSION_FIELD_EXIT_TOPIC,
			IProjectVariables.SESSION_FIELD_LASTERROR,
			IProjectVariables.SESSION_FIELD_MEDIATYPE,
			IProjectVariables.SESSION_FIELD_PROTOCOLNAME,
			IProjectVariables.SESSION_FIELD_PROTOCOLVERSION,
			IProjectVariables.SESSION_FIELD_SESSIONID,
			IProjectVariables.SESSION_FIELD_SESSIONLABEL,
			IProjectVariables.SESSION_FIELD_SHAREDMODE,
			IProjectVariables.SESSION_FIELD_UCID,
			IProjectVariables.SESSION_FIELD_UUI,
			IProjectVariables.SESSION_FIELD_VIDEOBITRATE,
			IProjectVariables.SESSION_FIELD_VIDEOCODEC,
			IProjectVariables.SESSION_FIELD_VIDEOENABLED,
			IProjectVariables.SESSION_FIELD_VIDEOFARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOFORMAT,
			IProjectVariables.SESSION_FIELD_VIDEOFPS,
			IProjectVariables.SESSION_FIELD_VIDEOHEIGHT,
			IProjectVariables.SESSION_FIELD_VIDEONEARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOWIDTH,
			IProjectVariables.SESSION_FIELD_VPCALLEDEXTENSION,
			IProjectVariables.SESSION_FIELD_VPCONVERSEONDATA,
			IProjectVariables.SESSION_FIELD_VPCOVERAGEREASON,
			IProjectVariables.SESSION_FIELD_VPCOVERAGETYPE,
			IProjectVariables.SESSION_FIELD_VPRDNIS,
			IProjectVariables.SESSION_FIELD_VPREPORTURL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SESSION, variableFields, null, session, false, true );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PAGE_NUMBER_FIELD_MENU_PAGE_NUMBER };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PAGE_NUMBER, variableFields, new String[] {"0"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REGION_SELECTION_FIELD_CONFIDENCE,
			IProjectVariables.REGION_SELECTION_FIELD_INPUTMODE,
			IProjectVariables.REGION_SELECTION_FIELD_INTERPRETATION,
			IProjectVariables.REGION_SELECTION_FIELD_NOINPUTCOUNT,
			IProjectVariables.REGION_SELECTION_FIELD_NOMATCHCOUNT,
			IProjectVariables.REGION_SELECTION_FIELD_UTTERANCE,
			IProjectVariables.REGION_SELECTION_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REGION_SELECTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_ERRORCODE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_MESSAGE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_OBJECT,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_STACKTRACE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DD_LAST_EXCEPTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.BLOOD__GROUP_FIELD_CONFIDENCE,
			IProjectVariables.BLOOD__GROUP_FIELD_INPUTMODE,
			IProjectVariables.BLOOD__GROUP_FIELD_INTERPRETATION,
			IProjectVariables.BLOOD__GROUP_FIELD_NOINPUTCOUNT,
			IProjectVariables.BLOOD__GROUP_FIELD_NOMATCHCOUNT,
			IProjectVariables.BLOOD__GROUP_FIELD_UTTERANCE,
			IProjectVariables.BLOOD__GROUP_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.BLOOD__GROUP, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CHOICE_URLS_FIELD_CHOICE_1,
			IProjectVariables.CHOICE_URLS_FIELD_CHOICE_2,
			IProjectVariables.CHOICE_URLS_FIELD_CHOICE_3,
			IProjectVariables.CHOICE_URLS_FIELD_CHOICE_4,
			IProjectVariables.CHOICE_URLS_FIELD_CHOICE_5,
			IProjectVariables.CHOICE_URLS_FIELD_CHOICE_6 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CHOICE_URLS, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TIME_FIELD_AUDIO,
			IProjectVariables.TIME_FIELD_HOUR,
			IProjectVariables.TIME_FIELD_MILLISECOND,
			IProjectVariables.TIME_FIELD_MINUTE,
			IProjectVariables.TIME_FIELD_SECOND,
			IProjectVariables.TIME_FIELD_TIMEZONE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TIME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SHAREDUUI_FIELD_ID,
			IProjectVariables.SHAREDUUI_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SHAREDUUI, variableFields, null, session, false, false );
		session.putVariable(variable);
	}
	/**
	 * This method returns the name of the application.
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public String getEntryName() {
		return("BloodBank");
	}
	/**
	 * This method returns a list of life cycle classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public java.util.Collection getPluggableLifeCycle() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns a list of VXML contributor classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public java.util.Collection getPluggableVXMLContrib() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns the root document for the application.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public String getRootDoc() {
		return("AppRoot");
	}
	/**
	 * This method returns a boolean to indicate if the approot node has a web page to show.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public boolean hasWebPage(com.avaya.sce.runtimecommon.SCESession mySession) {
		return false;
	}
	/**
	 * Builds the list of input parameters that are defined for this application 
	 * entry.  This list is built automatically by adding Input Parameter
	 * nodes to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>java.lang.String</code> objects that
	 * are the names of parameters the application is expecting.
	 * If the AppRoot node does not have any input parameters, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of capture expression that are defined for this application 
	 * entry.  This list is built automatically by adding Capture Expression
	 * items to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>CaptureExpression</code> objects that
	 * specify the ECMA script expression and the Orchestration Designer 
	 * session variable that will store the captured result.
	 * If the AppRoot node does not have any capture expression items, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2023-FEB-13  05:31:48 PM
	 */
	public java.util.Collection getCaptureExpressions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
}
